# Generated by Django 5.1.1 on 2024-10-11 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_admin', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_assigning_person', models.CharField(choices=[('Select who you are', 'Select who you are'), ('Admin', 'Admin'), ('Teacher', 'Teacher')], default='Select Who You Are', max_length=55)),
                ('course_name', models.CharField(max_length=65)),
                ('course_image', models.ImageField(blank=True, default='media/courseImg/pic.png', null=True, upload_to='courseImg/')),
                ('duration', models.CharField(max_length=45)),
                ('fees', models.IntegerField()),
                ('course_created_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=35)),
                ('lname', models.CharField(max_length=35)),
                ('guardian_name', models.CharField(max_length=35)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=35, unique=True)),
                ('mob', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=85)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=15)),
                ('pin', models.IntegerField()),
                ('role', models.CharField(choices=[('Select Role', 'Select Role'), ('Student', 'Student'), ('Teacher', 'Teacher')], default='Select Role', max_length=30)),
                ('gender', models.CharField(choices=[('Select Gender', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female')], default='Select Gender', max_length=20)),
                ('pic_student', models.ImageField(blank=True, default='media/profiles/pic1.png', null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoursesEnrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=65)),
                ('fees_paid', models.BooleanField(default=True)),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courses')),
                ('st_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='abc', max_length=35)),
                ('lname', models.CharField(default='xyz', max_length=35)),
                ('guardian_name', models.CharField(default=25, max_length=35)),
                ('age', models.IntegerField(default=25)),
                ('email', models.EmailField(default='abc@gmail.com', max_length=35)),
                ('mob', models.CharField(default='0909090909', max_length=12)),
                ('address', models.CharField(default='Ahm', max_length=85)),
                ('city', models.CharField(default='Ahm', max_length=15)),
                ('state', models.CharField(default='GJ', max_length=25)),
                ('country', models.CharField(default='India', max_length=15)),
                ('pin', models.IntegerField(default=111)),
                ('role', models.CharField(choices=[('Select Role', 'Select Role'), ('Student', 'Student'), ('Teacher', 'Teacher')], default='Select Role', max_length=30)),
                ('gender', models.CharField(choices=[('Select Gender', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female')], default='Select Gender', max_length=20)),
                ('teacher_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
    ]
