# Generated by Django 5.1.1 on 2024-10-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pic_student',
            field=models.ImageField(blank=True, default='profiles/pic1.png', null=True, upload_to='profiles/'),
        ),
    ]
