# Generated by Django 5.1.1 on 2024-10-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_pic_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_data',
        ),
        migrations.AddField(
            model_name='teacher',
            name='pic_teacher',
            field=models.ImageField(blank=True, default='profiles/pic1.png', null=True, upload_to='profiles/'),
        ),
    ]
