# Generated by Django 5.1.1 on 2024-10-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_teacher_teacher_data_teacher_pic_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesenrolled',
            name='course_name',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
