# Generated by Django 5.1.1 on 2024-10-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_teaching_person',
            field=models.CharField(blank=True, default='Tejas Bhatt', max_length=55, null=True),
        ),
    ]
