# Generated by Django 5.1.1 on 2024-10-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_courses_course_teaching_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='lecture_flow',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
