# Generated by Django 5.1.1 on 2024-10-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_studentattendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendence',
            name='stud_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='studentattendence',
            name='topic_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentattendence',
            name='topic_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='stud_present',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
