# Generated by Django 5.1.1 on 2024-10-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_studentattendence_stud_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendence',
            name='course_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
