# Generated by Django 5.1.1 on 2024-10-18 06:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_studentattendence_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courses')),
                ('stud_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
    ]
