# Generated by Django 5.1.1 on 2024-10-18 06:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_courseinquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinquery',
            name='inquiry_date_time',
        ),
        migrations.AddField(
            model_name='courseinquery',
            name='inquiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
